name: Code Style Check

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-style:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: 17
        java-distribution: adopt
        maven-version: 3.9.7
        settings-servers: |
          [{
            "id": "skyve",
            "username": "${{ secrets.NEXUSUSERNAME }}",
            "password": "${{ secrets.NEXUSPASSWORD }}"
          }]
    - name: Spotless Check
      run: mvn -B spotless:check
